title: Site

tabs:
  subpages:
    label: sections
    columns:
      left: 
        width: 1/2
        sticky: true
        sections: 
          subpages:
            type: pages
            headline: Sections
            template:
              - works
              - shows
              - curators
              - venues
              - garden
              - info
            create: false
            image: icon
      right:
        width: 1/2
        fields:
          lefthome:
            label: Home Left Image
            type: files
            layout: cards
            width: 1/2
            query: kirby.page("images").images
            uploads: false
            translate: false
          righthome:
            label: Home Right Image
            type: files
            layout: cards
            width: 1/2
            query: kirby.page("images").images
            uploads: false
            translate: false
  media:
    label: media
    sections:
      allimages:
        headline: Media
        type: files
        parent: kirby.page("images")
        template: image
        layout: cards
        translate: false
        size: small
        query: page.images
        info: '{{ file.caption }} {{file.credits}}'

