title: Site

tabs:
  subpages:
    label: sections
    sections: 
      subpages:
        type: pages
        headline: Sections
        template:
          - works
          - shows
          - curators
          - venues
          - garden
          - info
  media:
    label: media
    sections:
      allimages:
        headline: Media
        type: files
        parent: kirby.page("images")
        template: image
        layout: cards
        size: small
        query: page.images
        info: '{{ file.caption }} {{file.credits}}'
        translate: false

