title: Site

tabs:
  works:
    label: Works
    sections:
      workgroups:
        type: fields
        fields:
          workgroups:
            label: Work Groups
            type: tags
            help: Create work groups here          
      works:
        type: pages
        template: work
        parent: kirby.page("works")
        info: '{{page.datestart}} {{page.dateOrOngoing}} | {{page.group}} | Editions {{page.editionsammount}} | AP {{page.apammount}} '
        status: all
  shows:
    label: Shows
    sections:      
      shows:
        type: pages
        template: show
        parent: kirby.page("shows")          
        info: '{{page.datestart.toDate('d.m.Y')}} -> {{page.dateend.toDate('d.m.Y')}} | {{page.curator.inline}} | {{page.venue.inline}} , {{page.city}}'
        status: all
  info:

  images:
    label: Images
    sections:
      allimages:
        headline: Images
        type: files
        parent: kirby.page("images")
        template: image
        layout: cards
        size: medium
        query: page.images
        info: '{{ file.caption }} {{file.credits}}'
        translate: false
  meta:
    label: Meta
    columns:
      - width: 1/2
        sections:
          curators:
            type: pages
            template: curator
            parent: kirby.page("curators")
            sortBy: title desc
      - width: 1/2
        sections:
          venues:
            type: pages
            template: venue
            parent: kirby.page("venues")    
            sortBy: title desc
          workIndex:
            type: fields
            fields:
              workIndex:
                type: hidden          

